### ISSUE TITLE
make production library work in browser and node

### ISSUE THREAD

**Issue by JWally** [JWally/jsLPSolver#14]
Would like to have 1 file work in the browser environment (raw and asm) and in Node as well. Currently have 2 versions in existence (1 at prod/solver.js and the other at src/solver.js)

**Comment by JWally** [comment]
@bchevalier here's what I'm thinking of doing to fix the issue of needing 2 files to work in 2 environments; question is would it mess you up too much?

1. I'll rename ```src/solver.js``` to ```src/main.js```
2. I'll make it so running ```grunt prod``` will produce a browserfied version of the project at ```src/solver.js```. This way, the entry point to the project is always at ```src/solver.js```. This keeps the project from breaking anything that uses it as a dependency
3. At the bottom of the new browserfied ```src/solver.js``` file, I'll append a piece of code that looks something like this:

```javascript
  (function(){
    // Only execute if we're in node
    if(typeof module === "object"){
    // Have this file act as a facade
    // for src/main.js, which houses the
    // guts of this project
      module.exports = require("./main");
    }
  })()
```
Currently, the browserfied version of solver.js returns a blank object in the node environment. I think this'll fix that issue.

**Comment by bchevalier** [comment]
This is solution is fine by me, and if you think that will do it then go for it.

**Comment by bchevalier** [comment]
By the way, could you make a new npm release?

**Comment by JWally** [comment]
Done

**Comment by bchevalier** [comment]
thanks!
