### ISSUE TITLE
Use git tags to mark versions for bower registry

### ISSUE THREAD

**Issue by joshrickert** [JWally/jsLPSolver#17]
I noticed you have a version set in bower.json but there are no git tags to designate versions for the bower package registry, so it's a bit tough to properly use this as a dependency.

**Comment by bchevalier** [comment]
Actually it would be nice to publish a new npm release in the process

**Comment by bchevalier** [comment]
By the way, @joshrickert, I am curious about whether you managed to use this component or if you had any other problem with it?

**Comment by JWally** [comment]
That's on me. Sorry about that.
Will try and tidy everything up tomorrow.

**Comment by JWally** [comment]
Updated all to version 0.4.0.

**Comment by joshrickert** [comment]
Thanks for the quick response guys. I've been trying this out on my project, and it's been helpful, though it hasn't perfectly solved my use case. Since @bchevalier asked, I wrote up a description of that issue and opened a new ticket.

I see 0.4.0 on the bower registry now; nice work. I'll go ahead and close this one.
