### ISSUE TITLE
Solving too long

### ISSUE THREAD

**Issue by castek** [JWally/jsLPSolver#23]
Hello,
first I would like to thank Justin for this project.
The solver finds correct solution for many tasks (I have tested around 1000 tasks with 10-30 variables), many of them last less then second, but some of the tasks last very long (minutes, tens of minutes). Why? Is it possible to find the solution fast? I don't understand theory of LP. I give an example of the task that lasts too long. Thank you.

"{"constraints":{"c0":{"min":2.999},"c1":{"min":-3.001},"c2":{"min":3.999},"c3":{"min":-4.001},"c4":{"min":4.999},"c5":{"min":-5.001},"c6":{"min":2.999},"c7":{"min":-3.001},"c8":{"min":2.999},"c9":{"min":-3.001},"c10":{"min":3.999},"c11":{"min":-4.001},"c12":{"min":4.999},"c13":{"min":-5.001},"c14":{"min":3.999},"c15":{"min":-4.001},"c16":{"min":2.999},"c17":{"min":-3.001},"c18":{"min":2.999},"c19":{"min":-3.001},"c20":{"min":-22.001},"c21":{"min":-15.001},"c22":{"min":-0.001},"c23":{"min":-0.001},"c24":{"min":-0.001},"c25":{"min":-0.001},"c26":{"min":-0.001},"c27":{"min":-0.001},"c28":{"min":-0.001},"c29":{"min":-0.001},"c30":{"min":-0.001},"c31":{"min":-0.001},"c32":{"min":-0.001},"c33":{"min":-0.001},"c34":{"min":-0.001},"c35":{"min":-0.001},"c36":{"min":-0.001},"c37":{"min":-0.001},"c38":{"min":-0.001},"c39":{"min":-0.001},"c40":{"min":-0.001}},"variables":{"x0":{"objective":10,"c0":1,"c1":-1,"c2":0,"c3":0,"c4":0,"c5":0,"c6":0,"c7":0,"c8":0,"c9":0,"c10":0,"c11":0,"c12":0,"c13":0,"c14":0,"c15":0,"c16":0,"c17":0,"c18":0,"c19":0,"c20":-1,"c21":0,"c22":1,"c23":0,"c24":0,"c25":0,"c26":0,"c27":0,"c28":0,"c29":0,"c30":0,"c31":0,"c32":0,"c33":0,"c34":0,"c35":0,"c36":0,"c37":0,"c38":0,"c39":0,"c40":0},"x1":{"objective":10,"c0":0,"c1":0,"c2":1,"c3":-1,"c4":0,"c5":0,"c6":0,"c7":0,"c8":0,"c9":0,"c10":0,"c11":0,"c12":0,"c13":0,"c14":0,"c15":0,"c16":0,"c17":0,"c18":0,"c19":0,"c20":-1,"c21":0,"c22":0,"c23":1,"c24":0,"c25":0,"c26":0,"c27":0,"c28":0,"c29":0,"c30":0,"c31":0,"c32":0,"c33":0,"c34":0,"c35":0,"c36":0,"c37":0,"c38":0,"c39":0,"c40":0},"x2":{"objective":10,"c0":0,"c1":0,"c2":1,"c3":-1,"c4":0,"c5":0,"c6":0,"c7":0,"c8":0,"c9":0,"c10":0,"c11":0,"c12":0,"c13":0,"c14":0,"c15":0,"c16":0,"c17":0,"c18":0,"c19":0,"c20":0,"c21":-1,"c22":0,"c23":0,"c24":1,"c25":0,"c26":0,"c27":0,"c28":0,"c29":0,"c30":0,"c31":0,"c32":0,"c33":0,"c34":0,"c35":0,"c36":0,"c37":0,"c38":0,"c39":0,"c40":0},"x3":{"objective":10,"c0":0,"c1":0,"c2":0,"c3":0,"c4":1,"c5":-1,"c6":0,"c7":0,"c8":0,"c9":0,"c10":0,"c11":0,"c12":0,"c13":0,"c14":0,"c15":0,"c16":0,"c17":0,"c18":0,"c19":0,"c20":-1,"c21":0,"c22":0,"c23":0,"c24":0,"c25":1,"c26":0,"c27":0,"c28":0,"c29":0,"c30":0,"c31":0,"c32":0,"c33":0,"c34":0,"c35":0,"c36":0,"c37":0,"c38":0,"c39":0,"c40":0},"x4":{"objective":10,"c0":0,"c1":0,"c2":0,"c3":0,"c4":1,"c5":-1,"c6":0,"c7":0,"c8":0,"c9":0,"c10":0,"c11":0,"c12":0,"c13":0,"c14":0,"c15":0,"c16":0,"c17":0,"c18":0,"c19":0,"c20":0,"c21":-1,"c22":0,"c23":0,"c24":0,"c25":0,"c26":1,"c27":0,"c28":0,"c29":0,"c30":0,"c31":0,"c32":0,"c33":0,"c34":0,"c35":0,"c36":0,"c37":0,"c38":0,"c39":0,"c40":0},"x5":{"objective":10,"c0":0,"c1":0,"c2":0,"c3":0,"c4":0,"c5":0,"c6":1,"c7":-1,"c8":0,"c9":0,"c10":0,"c11":0,"c12":0,"c13":0,"c14":0,"c15":0,"c16":0,"c17":0,"c18":0,"c19":0,"c20":-1,"c21":0,"c22":0,"c23":0,"c24":0,"c25":0,"c26":0,"c27":1,"c28":0,"c29":0,"c30":0,"c31":0,"c32":0,"c33":0,"c34":0,"c35":0,"c36":0,"c37":0,"c38":0,"c39":0,"c40":0},"x6":{"objective":10,"c0":0,"c1":0,"c2":0,"c3":0,"c4":0,"c5":0,"c6":1,"c7":-1,"c8":0,"c9":0,"c10":0,"c11":0,"c12":0,"c13":0,"c14":0,"c15":0,"c16":0,"c17":0,"c18":0,"c19":0,"c20":0,"c21":-1,"c22":0,"c23":0,"c24":0,"c25":0,"c26":0,"c27":0,"c28":1,"c29":0,"c30":0,"c31":0,"c32":0,"c33":0,"c34":0,"c35":0,"c36":0,"c37":0,"c38":0,"c39":0,"c40":0},"x7":{"objective":10,"c0":0,"c1":0,"c2":0,"c3":0,"c4":0,"c5":0,"c6":0,"c7":0,"c8":1,"c9":-1,"c10":0,"c11":0,"c12":0,"c13":0,"c14":0,"c15":0,"c16":0,"c17":0,"c18":0,"c19":0,"c20":-1,"c21":0,"c22":0,"c23":0,"c24":0,"c25":0,"c26":0,"c27":0,"c28":0,"c29":1,"c30":0,"c31":0,"c32":0,"c33":0,"c34":0,"c35":0,"c36":0,"c37":0,"c38":0,"c39":0,"c40":0},"x8":{"objective":10,"c0":0,"c1":0,"c2":0,"c3":0,"c4":0,"c5":0,"c6":0,"c7":0,"c8":1,"c9":-1,"c10":0,"c11":0,"c12":0,"c13":0,"c14":0,"c15":0,"c16":0,"c17":0,"c18":0,"c19":0,"c20":0,"c21":-1,"c22":0,"c23":0,"c24":0,"c25":0,"c26":0,"c27":0,"c28":0,"c29":0,"c30":1,"c31":0,"c32":0,"c33":0,"c34":0,"c35":0,"c36":0,"c37":0,"c38":0,"c39":0,"c40":0},"x9":{"objective":10,"c0":0,"c1":0,"c2":0,"c3":0,"c4":0,"c5":0,"c6":0,"c7":0,"c8":0,"c9":0,"c10":1,"c11":-1,"c12":0,"c13":0,"c14":0,"c15":0,"c16":0,"c17":0,"c18":0,"c19":0,"c20":-1,"c21":0,"c22":0,"c23":0,"c24":0,"c25":0,"c26":0,"c27":0,"c28":0,"c29":0,"c30":0,"c31":1,"c32":0,"c33":0,"c34":0,"c35":0,"c36":0,"c37":0,"c38":0,"c39":0,"c40":0},"x10":{"objective":10,"c0":0,"c1":0,"c2":0,"c3":0,"c4":0,"c5":0,"c6":0,"c7":0,"c8":0,"c9":0,"c10":1,"c11":-1,"c12":0,"c13":0,"c14":0,"c15":0,"c16":0,"c17":0,"c18":0,"c19":0,"c20":0,"c21":-1,"c22":0,"c23":0,"c24":0,"c25":0,"c26":0,"c27":0,"c28":0,"c29":0,"c30":0,"c31":0,"c32":1,"c33":0,"c34":0,"c35":0,"c36":0,"c37":0,"c38":0,"c39":0,"c40":0},"x11":{"objective":10,"c0":0,"c1":0,"c2":0,"c3":0,"c4":0,"c5":0,"c6":0,"c7":0,"c8":0,"c9":0,"c10":0,"c11":0,"c12":1,"c13":-1,"c14":0,"c15":0,"c16":0,"c17":0,"c18":0,"c19":0,"c20":-1,"c21":0,"c22":0,"c23":0,"c24":0,"c25":0,"c26":0,"c27":0,"c28":0,"c29":0,"c30":0,"c31":0,"c32":0,"c33":1,"c34":0,"c35":0,"c36":0,"c37":0,"c38":0,"c39":0,"c40":0},"x12":{"objective":10,"c0":0,"c1":0,"c2":0,"c3":0,"c4":0,"c5":0,"c6":0,"c7":0,"c8":0,"c9":0,"c10":0,"c11":0,"c12":1,"c13":-1,"c14":0,"c15":0,"c16":0,"c17":0,"c18":0,"c19":0,"c20":0,"c21":-1,"c22":0,"c23":0,"c24":0,"c25":0,"c26":0,"c27":0,"c28":0,"c29":0,"c30":0,"c31":0,"c32":0,"c33":0,"c34":1,"c35":0,"c36":0,"c37":0,"c38":0,"c39":0,"c40":0},"x13":{"objective":10,"c0":0,"c1":0,"c2":0,"c3":0,"c4":0,"c5":0,"c6":0,"c7":0,"c8":0,"c9":0,"c10":0,"c11":0,"c12":0,"c13":0,"c14":1,"c15":-1,"c16":0,"c17":0,"c18":0,"c19":0,"c20":-1,"c21":0,"c22":0,"c23":0,"c24":0,"c25":0,"c26":0,"c27":0,"c28":0,"c29":0,"c30":0,"c31":0,"c32":0,"c33":0,"c34":0,"c35":1,"c36":0,"c37":0,"c38":0,"c39":0,"c40":0},"x14":{"objective":10,"c0":0,"c1":0,"c2":0,"c3":0,"c4":0,"c5":0,"c6":0,"c7":0,"c8":0,"c9":0,"c10":0,"c11":0,"c12":0,"c13":0,"c14":1,"c15":-1,"c16":0,"c17":0,"c18":0,"c19":0,"c20":0,"c21":-1,"c22":0,"c23":0,"c24":0,"c25":0,"c26":0,"c27":0,"c28":0,"c29":0,"c30":0,"c31":0,"c32":0,"c33":0,"c34":0,"c35":0,"c36":1,"c37":0,"c38":0,"c39":0,"c40":0},"x15":{"objective":10,"c0":0,"c1":0,"c2":0,"c3":0,"c4":0,"c5":0,"c6":0,"c7":0,"c8":0,"c9":0,"c10":0,"c11":0,"c12":0,"c13":0,"c14":0,"c15":0,"c16":1,"c17":-1,"c18":0,"c19":0,"c20":-1,"c21":0,"c22":0,"c23":0,"c24":0,"c25":0,"c26":0,"c27":0,"c28":0,"c29":0,"c30":0,"c31":0,"c32":0,"c33":0,"c34":0,"c35":0,"c36":0,"c37":1,"c38":0,"c39":0,"c40":0},"x16":{"objective":10,"c0":0,"c1":0,"c2":0,"c3":0,"c4":0,"c5":0,"c6":0,"c7":0,"c8":0,"c9":0,"c10":0,"c11":0,"c12":0,"c13":0,"c14":0,"c15":0,"c16":1,"c17":-1,"c18":0,"c19":0,"c20":0,"c21":-1,"c22":0,"c23":0,"c24":0,"c25":0,"c26":0,"c27":0,"c28":0,"c29":0,"c30":0,"c31":0,"c32":0,"c33":0,"c34":0,"c35":0,"c36":0,"c37":0,"c38":1,"c39":0,"c40":0},"x17":{"objective":10,"c0":0,"c1":0,"c2":0,"c3":0,"c4":0,"c5":0,"c6":0,"c7":0,"c8":0,"c9":0,"c10":0,"c11":0,"c12":0,"c13":0,"c14":0,"c15":0,"c16":0,"c17":0,"c18":1,"c19":-1,"c20":-1,"c21":0,"c22":0,"c23":0,"c24":0,"c25":0,"c26":0,"c27":0,"c28":0,"c29":0,"c30":0,"c31":0,"c32":0,"c33":0,"c34":0,"c35":0,"c36":0,"c37":0,"c38":0,"c39":1,"c40":0},"x18":{"objective":10,"c0":0,"c1":0,"c2":0,"c3":0,"c4":0,"c5":0,"c6":0,"c7":0,"c8":0,"c9":0,"c10":0,"c11":0,"c12":0,"c13":0,"c14":0,"c15":0,"c16":0,"c17":0,"c18":1,"c19":-1,"c20":0,"c21":-1,"c22":0,"c23":0,"c24":0,"c25":0,"c26":0,"c27":0,"c28":0,"c29":0,"c30":0,"c31":0,"c32":0,"c33":0,"c34":0,"c35":0,"c36":0,"c37":0,"c38":0,"c39":0,"c40":1}},"ints":{"x0":1,"x1":1,"x2":1,"x3":1,"x4":1,"x5":1,"x6":1,"x7":1,"x8":1,"x9":1,"x10":1,"x11":1,"x12":1,"x13":1,"x14":1,"x15":1,"x16":1,"x17":1,"x18":1},"optimize":"objective","opType":"min"}"

**Comment by bchevalier** [comment]
Hi,

Thank you for the feedback. I will have a look but my first guess is that it is difficult for the solver to find a solution with integer values considering that the given constraints are very close to integer values but not quite: for instance ```"c0":{"min":2.999}``` instead of ```"c0":{"min":3}```. Is this how your model is supposed to be?

also, is the constraint ```"c40":{"min":-0.001}``` useful? Since all the variables are strictly positive, this constraint is useless.

**Comment by bchevalier** [comment]
I think I know how to make your problem be solved in less than a second by adding a simple mechanism in the Simplex. Does your life depend on it?

**Comment by castek** [comment]
I'm comparing results with some other solvers, some of them needs the constraints in form of "c40":{"min":-0.001} though each of them has nonnegative variables. I may try it without these >= 0 constraints. 

> I think I know how to make your problem be solved in less than a second by adding a simple mechanism in the Simplex. Does your life depend on it?

Yes, what is your solution?

Thank

**Comment by castek** [comment]
The constraints are of three types:
1) eg. x2 + x3 + x4 = 7,
this returned NaNs for many inputs, so I substituted it with two inequalities:
x2 + x3 + x4 >= 6.999 and
x2 + x3 + x4 <= 7.001
This substitution helped a lot.
2) sum of some variables <= some positive integer (eg. "c21" <= 15)
this I substituted with:
sum of some variables <= some positive integer + epsilon
eg.
sum of some variables <= 15.001
3) each variable >= 0
that I substituted with:
each variable >= -epsilon
eg.
each variable >= -0.001

If there is more than one possible solution with equal minimum value, it's enough to get any solution.

**Comment by bchevalier** [comment]
By when will you need it?

Actually if you remove this trick, it works perfectly fine on the problem you gave, I get a result in 5ms.

**Comment by bchevalier** [comment]
The JSLPSolver was returning NaNs for some inputs? if that's the case, can you also give us the model that returns NaNs?

**Comment by bchevalier** [comment]
By the way the trick I was thinking about was to add tests on each constraint, if they exclusively contain integer variables then it is possible to round the right-hand-side to an integer value. Which allows your problem to be solved instantly.

**Comment by bchevalier** [comment]
Let us know whether you still have numeric instabilities or if reformulating the model solved your issue. By the way, which other solver did you try to use?

**Comment by JWally** [comment]
Indeed, curious to know what other solver you tried against this.

For what its worth, this library has a function "ReformatLP" which converts a model into a more normal looking LP:

```
min: 10 x0 10 x1 10 x2 10 x3 10 x4 10 x5 10 x6 10 x7 10 x8 10 x9 10 x10 10 x11 10 x12 10 x13 10 x14 10 x15 10 x16 10 x17 10 x18;
 1 x0 >= 2.999;
 -1 x0 >= -3.001;
 1 x1 1 x2 >= 3.999;
 -1 x1 -1 x2 >= -4.001;
 1 x3 1 x4 >= 4.999;
 -1 x3 -1 x4 >= -5.001;
 1 x5 1 x6 >= 2.999;
 -1 x5 -1 x6 >= -3.001;
 1 x7 1 x8 >= 2.999;
 -1 x7 -1 x8 >= -3.001;
 1 x9 1 x10 >= 3.999;
 -1 x9 -1 x10 >= -4.001;
 1 x11 1 x12 >= 4.999;
 -1 x11 -1 x12 >= -5.001;
 1 x13 1 x14 >= 3.999;
 -1 x13 -1 x14 >= -4.001;
 1 x15 1 x16 >= 2.999;
 -1 x15 -1 x16 >= -3.001;
 1 x17 1 x18 >= 2.999;
 -1 x17 -1 x18 >= -3.001;
 -1 x0 -1 x1 -1 x3 -1 x5 -1 x7 -1 x9 -1 x11 -1 x13 -1 x15 -1 x17 >= -22.001;
 -1 x2 -1 x4 -1 x6 -1 x8 -1 x10 -1 x12 -1 x14 -1 x16 -1 x18 >= -15.001;
 1 x0 >= -0.001;
 1 x1 >= -0.001;
 1 x2 >= -0.001;
 1 x3 >= -0.001;
 1 x4 >= -0.001;
 1 x5 >= -0.001;
 1 x6 >= -0.001;
 1 x7 >= -0.001;
 1 x8 >= -0.001;
 1 x9 >= -0.001;
 1 x10 >= -0.001;
 1 x11 >= -0.001;
 1 x12 >= -0.001;
 1 x13 >= -0.001;
 1 x14 >= -0.001;
 1 x15 >= -0.001;
 1 x16 >= -0.001;
 1 x17 >= -0.001;
 1 x18 >= -0.001;


int x0;
int x1;
int x2;
int x3;
int x4;
int x5;
int x6;
int x7;
int x8;
int x9;
int x10;
int x11;
int x12;
int x13;
int x14;
int x15;
int x16;
int x17;
int x18;
```

when I run this in LP_Solve ([Link Here](http://lpsolve.sourceforge.net/5.5/)), it spits out the following:
```
Value of objective function: 370.00000000

Actual values of the variables:
x0                              3
x2                              4
x4                              5
x6                              3
x8                              3
x9                              4
x11                             5
x13                             4
x15                             3
x17                             3
```

Fun side note, you can also import this in as a text file, run it through ```solver.reformatLP(text)``` and it will convert it to a JSON model.

**Comment by JWally** [comment]
Like Brice said, a cleaner approach would be to have a model with equality constraints:

```
min: 10 x0 10 x1 10 x2 10 x3 10 x4 10 x5 10 x6 10 x7 10 x8 10 x9 10 x10 10 x11 10 x12 10 x13 10 x14 10 x15 10 x16 10 x17 10 x18;
 1 x0 >= 3;
 1 x1 1 x2 = 4;
 1 x3 1 x4 = 5;
 1 x5 1 x6 = 3;
 1 x7 1 x8 = 3;
 1 x9 1 x10 = 4;
 1 x11 1 x12 = 5;
 1 x13 1 x14 = 4;
 1 x15 1 x16 = 3;
 1 x17 1 x18 = 3;
 -1 x0 -1 x1 -1 x3 -1 x5 -1 x7 -1 x9 -1 x11 -1 x13 -1 x15 -1 x17 >= -22.001;
 -1 x2 -1 x4 -1 x6 -1 x8 -1 x10 -1 x12 -1 x14 -1 x16 -1 x18 >= -15.001;



int x0;
int x1;
int x2;
int x3;
int x4;
int x5;
int x6;
int x7;
int x8;
int x9;
int x10;
int x11;
int x12;
int x13;
int x14;
int x15;
int x16;
int x17;
int x18;
```

which turns into this:

```
{ opType: 'min',
  optimize: '_obj',
  constraints: 
   { __1: { min: 3 },
     __2: { equal: 4 },
     __3: { equal: 5 },
     __4: { equal: 3 },
     __5: { equal: 3 },
     __6: { equal: 4 },
     __7: { equal: 5 },
     __8: { equal: 4 },
     __9: { equal: 3 },
     __10: { equal: 3 },
     __11: { min: -22.001 },
     __12: { min: -15.001 } },
  variables: 
   { x0: { _obj: 10, __1: 1, __11: -1 },
     x1: { _obj: 10, __2: 1, __11: -1 },
     x2: { _obj: 10, __2: 1, __12: -1 },
     x3: { _obj: 10, __3: 1, __11: -1 },
     x4: { _obj: 10, __3: 1, __12: -1 },
     x5: { _obj: 10, __4: 1, __11: -1 },
     x6: { _obj: 10, __4: 1, __12: -1 },
     x7: { _obj: 10, __5: 1, __11: -1 },
     x8: { _obj: 10, __5: 1, __12: -1 },
     x9: { _obj: 10, __6: 1, __11: -1 },
     x10: { _obj: 10, __6: 1, __12: -1 },
     x11: { _obj: 10, __7: 1, __11: -1 },
     x12: { _obj: 10, __7: 1, __12: -1 },
     x13: { _obj: 10, __8: 1, __11: -1 },
     x14: { _obj: 10, __8: 1, __12: -1 },
     x15: { _obj: 10, __9: 1, __11: -1 },
     x16: { _obj: 10, __9: 1, __12: -1 },
     x17: { _obj: 10, __10: 1, __11: -1 },
     x18: { _obj: 10, __10: 1, __12: -1 } },
  ints: 
   { x0: 1,
     x1: 1,
     x2: 1,
     x3: 1,
     x4: 1,
     x5: 1,
     x6: 1,
     x7: 1,
     x8: 1,
     x9: 1,
     x10: 1,
     x11: 1,
     x12: 1,
     x13: 1,
     x14: 1,
     x15: 1,
     x16: 1,
     x17: 1,
     x18: 1 } }
```

which solves into:

```
{ feasible: true,
  result: 370,
  x0: 3,
  x4: 5,
  x6: 3,
  x8: 3,
  x7: 0,
  x9: 4,
  x11: 5,
  x13: 4,
  x15: 3,
  x17: 3,
  x2: 4 }
```

**Comment by castek** [comment]
Guys, you are right. I was so mindblinded by the previous solvers that I thought it's better to make inequalities with epsilon rather than equalities. I tried make it simpler as you said and 5000 tasks were solved in few seconds.
My final goal is QP over the same constraints. I'm using accord (c#) and node-quadprog (javascript) for solving QP. But these solvers sometimes find no solution (though the task has the solution). If QP finds no solution then I use your LP (the same objective but without quadratic members only). It's better to have at least some solution than no solution at all, but I would prefer solution of QP than LP.
jsLPSolver does not return NaNs, node-quadprog sometimes returns NaNs.
Many thanks

**Comment by bchevalier** [comment]
Ah I see, thanks for the feedback and it is interesting to hear that you want to solve QP problems because I plan on integrating a QP solver into JSLP sometime in 2016. I started the implementation but it will take time to finish (it is a bit challenging to do it right) and for the moment I can only solve convex problems (e.g ```min x * x```) and not concave problems (e.g ```max x * x ```).

By the way, I do not know if you want to get the best performances, but if you do, you can try using the function API instead of inputting JSONs (I guess it also depends on where your models come from). There is an example in ```test/functionApi.js```.
