### ISSUE TITLE
Parsing lp formatted files

### ISSUE THREAD

**Issue by lvenerosy** [JWally/jsLPSolver#33]
@JWally 

I found this problem http://miplib.zib.de/miplib2010/ns1766074.php and I converted the mps file into an lp one with lp_solve (lp_solve -parse_only -fmps ns1766074.mps -wlp ns1766074.lp) since the comments in Reformat.js mention lp_solver (you will find the lp file of the instance and the js file I use to generate the model in the archive below).

The problem is that even though it goes through the parsing, the solution is not the expected one and the parser seems to consider everything as a variable (even the 'cXX:' in front of the constraints). Is it possible for you to adapt the parser ? Because mps files seem to be popular (and there is just a command to go from mps to lp).

[Archive.zip](https://github.com/JWally/jsLPSolver/files/150452/Archive.zip)

**Comment by lvenerosy** [comment]
It is fine now, so I close the issue.

**Comment by bchevalier** [comment]
Actually, @lvenerosy , issues are usually closed when the PR has been merged (https://github.com/JWally/jsLPSolver/pull/35)
