### ISSUE TITLE
reformatLP is not working

### ISSUE THREAD

**Issue by robert197** [JWally/jsLPSolver#45]
reformatLP function is reformating into LP format but not from LP format into JSON object!

**Comment by bchevalier** [comment]
Hi,

Sorry it might not always work because it has not been extensively used.
Could you provide the LP file you are trying to convert so that we can test it?

**Comment by JWally** [comment]
@robert197 sorry its take me so long to get to this. 
Do you have an example where it fails that I could work with?
Thanks!
-JWW

**Comment by JWally** [comment]
gonna close for now. Feel free to create a new issue if its still broken.
