### ISSUE TITLE
How can we optimize with the bag

### ISSUE THREAD

**Issue by amandalmia14** [JWally/jsLPSolver#49]
Hi All,

I have a small doubt regarding linear programming (jsLPSolver) 

var solver = require("./src/solver"),
    model = 
    {
    "optimize": "price",
    "constraints": {
            "carb": {"equal": 80},  // 80 is in kg
            "protein": {"equal": 25},
            "fat": {"equal": 21}
    },
    "variables": {
        // Format 
        // Fruit {contents : % ..... , price of each fruit}.
        "Product1": {"carb": .46,"protein": 0.0,"fat": 0.0,"vita": 0.0, "iron": 0.0,"price":5.94,"Product1":1}, 
        "Product2": {"carb": .10,"protein": .18,"fat": 0,"vita": 0, "iron": 0.0,"price":7.0,"Product2":1},
        "Product3": {"carb": .18,"protein": .46,"fat": 0,"vita": 0, "iron": 0.0,"price":24.0,"Product3":1},
        "Product4": {"carb": 0,"protein": 0,"fat": .60,"vita": 0.0, "iron": 0.0,"price":11.14,"Product4":1}        
    }
    }
    
console.log(solver.Solve(model));
-------------------------------------------------------------------
Results : 
{ feasible: true,
  result: 2215.8178744
  bounded: true,
  Product1: 143.71980676,
  Product2: 138.88888889,
  Product4: 35 
}
**************************************************************************

DETAILS: 
Let say we have 4 different bags in which we can put max 50 kg of these products (Product1 /  Product2 / Product3 / Product4) 
i.e Bag1 contains 50kg of Product1, Bag2 contains 50kg of Product2 and so on..

Bag1 price is 247 (50 * 5.94)
Bag2 price is 350 (50 * 7)
Bag3 price is 1200 (50 * 24)
Bag4 price is 557 (50 * 11.14)

HOW TO MODIFY:
In the above case we are dealing with the minimum price solution with the given constraints. 

In the above results I need to increase / decrease the quantities (Products ) in such a way that minimum cost is involved. 
As the total actual cost would be (by the above results)
3 Bags of Product1, 3 bags of Product2, 1 Bag of Product4 (The fruits does come is 50kg pack ) 

=(3 * 247 + 3 * 350 +1 *557 ) 

How to make the solution more better by keeping it such a way that involves min cost but keeping the same constraints.

**Brice can you please help me out.**
Thanks

**Comment by bchevalier** [comment]
Hi Dalmam,

If I understand correctly:
You have 4 different types of bags.
And you want to determine how many of each type you need to satisfy the given requirements (carb, protein and fat).
While minimizing the price.

The first thing you have to do is turn your variables into integer variables, your problem becomes the following:
```javascript
{
	"optimize": "price",
	"constraints": {
		"carb":    { "equal": 80 },
		"protein": { "equal": 25 },
		"fat":     { "equal": 21 }
	},
	"variables": {
		"Product1": { "carb": 23, "protein": 0,  "fat": 0,  "vita": 0, "iron": 0, "price": 297,  "Product1": 1 },
		"Product2": { "carb": 5,  "protein": 9,  "fat": 0,  "vita": 0, "iron": 0, "price": 350,  "Product2": 1 },
		"Product3": { "carb": 9,  "protein": 23, "fat": 0,  "vita": 0, "iron": 0, "price": 1200, "Product3": 1 },
		"Product4": { "carb": 0,  "protein": 0,  "fat": 30, "vita": 0, "iron": 0, "price": 557,  "Product4": 1 }
	},
	"ints": {
		"Product1": 1,
		"Product2": 1,
		"Product3": 1,
		"Product4": 1
	}
}
```
***You will notice that the quantities for each variables have been multiplied by 50*** so when a variable, for instance Product1, is equal to 1 then it corresponds to buying a full 50kg bag of the given fruit.
The ```ints``` properties is here to specify that the variables can only have integer values.

I haven't tried solving it, ***but the main issue is that you might not be able to exactly satisfy the equality constraints for the requirements*** (carb, protein and fat). I can imagine two ways to relax the problem so that it becomes feasible:
(1) - The requirements only need to be roughly met (constraints will be relaxed)
(2) - The requirements are lower bounds (constraints will change from equality to minimum requirements)

In case you want to go for solution (1), your problem could be modified into:
```json
{
    "name": "Fruit Selection",
    "constraints": {
        "carb":    { "equal": 80, "weight": 1 },
        "protein": { "equal": 25, "weight": 1 },
        "fat":     { "equal": 21, "weight": 1 }
    },
    "variables": {
        "Product1": { "carb": 23, "protein": 0,  "fat": 0,  "vita": 0, "iron": 0, "price": 297,  "Product1": 1 },
        "Product2": { "carb": 5,  "protein": 9,  "fat": 0,  "vita": 0, "iron": 0, "price": 350,  "Product2": 1 },
        "Product3": { "carb": 9,  "protein": 23, "fat": 0,  "vita": 0, "iron": 0, "price": 1200, "Product3": 1 },
        "Product4": { "carb": 0,  "protein": 0,  "fat": 30, "vita": 0, "iron": 0, "price": 557,  "Product4": 1 }
    },
    "ints": {
        "Product1": 1,
        "Product2": 1,
        "Product3": 1,
        "Product4": 1
    }
}
```
***Notice that weights have been added to the constraints to relax and they do not need to be exactly satisfied anymore. Also, in this case you have to get rid of the price for the problem to be solved correctly***

Another way to go for solution (1), is by modifying your problem into:
```json
{
    "name": "Fruit Selection",
    "optimize": "price",
    "opType": "min",
    "constraints": {
        "carb":    { "equal": 80 },
        "protein": { "equal": 25 },
        "fat":     { "equal": 21 }
    },
    "variables": {
        "Product1": { "carb": 23, "protein": 0,  "fat": 0,  "vita": 0, "iron": 0, "price": 297,  "Product1": 1 },
        "Product2": { "carb": 5,  "protein": 9,  "fat": 0,  "vita": 0, "iron": 0, "price": 350,  "Product2": 1 },
        "Product3": { "carb": 9,  "protein": 23, "fat": 0,  "vita": 0, "iron": 0, "price": 1200, "Product3": 1 },
        "Product4": { "carb": 0,  "protein": 0,  "fat": 30, "vita": 0, "iron": 0, "price": 557,  "Product4": 1 },
        "carbSurplus": { "carb": 1, "price": 2000 },
        "proteinSurplus": { "protein": 1, "price": 2000 },
        "fatSurplus": { "fat": 1, "price": 2000 },
        "carbSlack": { "carb": -1, "price": 2000 },
        "proteinSlack": { "protein": -1, "price": 2000 },
        "fatSlack": { "fat": -1, "price": 2000 }
    },
    "ints": {
        "Product1": 1,
        "Product2": 1,
        "Product3": 1,
        "Product4": 1
    }
}
```
***Notice that we are adding a penalty to the gap to the requirements by adding a virtual price of 2000 per gap unit. Changing this penalty may change the result you obtain. Also, to get the actual total cost of your bags, you would need to remove the penalty cost.***

If you choose to go for solution (2), your problem could be modified into:
```json
{
	"optimize": "price",
	"constraints": {
		"carb":    { "min": 80 },
		"protein": { "min": 25 },
		"fat":     { "min": 21 }
	},
	"variables": {
		"Product1": { "carb": 23, "protein": 0,  "fat": 0,  "vita": 0, "iron": 0, "price": 297,  "Product1": 1 },
		"Product2": { "carb": 5,  "protein": 9,  "fat": 0,  "vita": 0, "iron": 0, "price": 350,  "Product2": 1 },
		"Product3": { "carb": 9,  "protein": 23, "fat": 0,  "vita": 0, "iron": 0, "price": 1200, "Product3": 1 },
		"Product4": { "carb": 0,  "protein": 0,  "fat": 30, "vita": 0, "iron": 0, "price": 557,  "Product4": 1 }
	},
	"ints": {
		"Product1": 1,
		"Product2": 1,
		"Product3": 1,
		"Product4": 1
	}
}
```
***Notice that equality constraints have been turned into lower bounds***.

All these solutions give different results. I hope at least one definition correspond to what you want and that you will be satisfied with the obtained result.
Do not hesitate if you need further help.

**Comment by lvenerosy** [comment]
Or you could do it this way if I understood correctly what you want to achieve : 

```
{
    "optimize": "price",
    "constraints": {
    "carb": {"min": 80},
    "protein": {"min": 25},
    "fat": {"min": 21},
    "bagsPrice": {"max": 0, "priority": 1}
},
    "variables": {
        "bag1": {"carb": 23,"protein": 0.0,"fat": 0.0,"vita": 0.0, "iron": 0.0,"price":0,"bagsPrice":297,"bag1":1},
        "bag2": {"carb": 5,"protein": 9,"fat": 0,"vita": 0, "iron": 0.0,"price":0,"bagsPrice":350,"bag2":1},
        "bag3": {"carb": 9,"protein": 23,"fat": 0,"vita": 0, "iron": 0.0,"price":0,"bagsPrice":1200,"bag3":1},
        "bag4": {"carb": 0,"protein": 0,"fat": 30,"vita": 0.0, "iron": 0.0,"price":0,"bagsPrice":574,"bag4":1}
    },
    "ints": {
        "bag1": 1,
        "bag2": 1,
        "bag3": 1,
        "bag4": 1
    }
}
```

Here your 3 main constraints are changed into lower bounds to be sure that there is a solution while still meeting the requirements. ```bagsPrice``` is a constraint that enforces that the price is at much 0 but it is relaxed with a priority of 1, meaning that the solver will try to have it be satisfied while keeping the problem optimized according to the main constraints. So in the end this constraint will not be satisfied but by trying to do it so, the solver will reduce as much as possible the cost.

In the solution the price can be seen as ```r1``` which is the relaxation variable associated to ```bagsPrice```.

**Comment by lvenerosy** [comment]
I didn't read @bchevalier post well enough, his solution 2 is better than the one I made.

**Comment by bchevalier** [comment]
Hi again Aman,

Thanks to @lvenerosy 's post, I realized there was a better way to go for solution (1):
```json
{
    "name": "Fruit Selection",
    "constraints": {
        "carb":    { "equal": 80, "priority": 1 },
        "protein": { "equal": 25, "priority": 1 },
        "fat":     { "equal": 21, "priority": 1 },
        "price":   { "max": 0, "priority": 2 }
    },
    "variables": {
        "Product1": { "carb": 23, "protein": 0,  "fat": 0,  "vita": 0, "iron": 0, "price": 297,  "Product1": 1 },
        "Product2": { "carb": 5,  "protein": 9,  "fat": 0,  "vita": 0, "iron": 0, "price": 350,  "Product2": 1 },
        "Product3": { "carb": 9,  "protein": 23, "fat": 0,  "vita": 0, "iron": 0, "price": 1200, "Product3": 1 },
        "Product4": { "carb": 0,  "protein": 0,  "fat": 30, "vita": 0, "iron": 0, "price": 557,  "Product4": 1 }
    },
    "ints": {
        "Product1": 1,
        "Product2": 1,
        "Product3": 1,
        "Product4": 1
    }
}
```
*** Here the requirements will be met as close as possible, and then the price will be minimized".

And to summarize, if you want to go for solution (2), here is the formulation that seems best:
{
	"optimize": "price",
	"constraints": {
		"carb":    { "min": 80 },
		"protein": { "min": 25 },
		"fat":     { "min": 21 }
	},
	"variables": {
		"Product1": { "carb": 23, "protein": 0,  "fat": 0,  "vita": 0, "iron": 0, "price": 297,  "Product1": 1 },
		"Product2": { "carb": 5,  "protein": 9,  "fat": 0,  "vita": 0, "iron": 0, "price": 350,  "Product2": 1 },
		"Product3": { "carb": 9,  "protein": 23, "fat": 0,  "vita": 0, "iron": 0, "price": 1200, "Product3": 1 },
		"Product4": { "carb": 0,  "protein": 0,  "fat": 30, "vita": 0, "iron": 0, "price": 557,  "Product4": 1 }
	},
	"ints": {
		"Product1": 1,
		"Product2": 1,
		"Product3": 1,
		"Product4": 1
	}
}

**Comment by amandalmia14** [comment]
Hi @bchevalier  

Thanks it really help in solving my issue.

I have one more question, the output of 

`{
    "constraints": {
        "carb":    { "equal": 80, "priority": 1 },
        "protein": { "equal": 25, "priority": 1 },
        "fat":     { "equal": 21, "priority": 1 },
        "price":   { "max": 0, "priority": 2 }
    },
    "variables": {
        "Product1": { "carb": 60, "protein": 0,  "fat": 0,  "vita": 0, "iron": 0, "price": 297,  "Product1": 1 },
        "Product2": { "carb": 5,  "protein": 9,  "fat": 0,  "vita": 0, "iron": 0, "price": 350,  "Product2": 1 },
        "Product3": { "carb": 9,  "protein": 23, "fat": 0,  "vita": 0, "iron": 0, "price": 1200, "Product3": 1 },
        "Product4": { "carb": 0,  "protein": 0,  "fat": 30, "vita": 0, "iron": 0, "price": 557,  "Product4": 1 }
    },
    "ints": {
        "Product1": 1,
        "Product2": 1,
        "Product3": 1,
        "Product4": 1
    }
    }
`

Its output is 

{ feasible: true,
  result: 0,
  bounded: true,
  r4: 1904,
  r1: 5,
  r2: 2,
  Product4: 1,
  r3: 9,
  Product1: 1,
  Product2: 3
 } 

1)Since the output is giving me the no of bags of each product is it possible to get what is the exact amount of product is been used ?
2) What is r1,r2,r3,r4 stands for?

Thanks 
-Aman

**Comment by bchevalier** [comment]
1) To get the exact amount of product, you should multiply the value of each variable by 50:
amount of Product4 = 1 * 50kg
amount of Product1 = 1 * 50kg
amount of Product3 = 3 * 50kg

2) r1,r2,r3,r4 stands for the relaxation of each constraint:
In general, ```ri = x``` means that constraint ```i``` was violated by an amount of ```x``` units
(It's true that it would be best if the relaxation variables had more straightforward names such as ```relaxationCarbs```, something we will try to fix).

r1 = 5, means that you are missing the carbs requirements by 5 units.
r2 = 2, means that you are missing the protein requirements by 2 units.
r3 = 9, means that you are missing the fat requirements by 9 units.
r4 = 1904 means that you are missing the price requirement (max 0) by 1904 units, in other words, the total price is 1904.

**Comment by amandalmia14** [comment]
Hi  @bchevalier ,

The exact amount I want to say that 

As you said r1, r2... are the relaxation of each constraint, since I have given each constraint having a "**equal**" property then it shouldn't be  decrease/increase.
If I had given "**max**" then it might be possible that the requirement can be less as I had define the max limit of the required product. 


Thanks
-Aman

**Comment by bchevalier** [comment]
Hi Aman, wondering if this issue could be closed? is your problem solved?

**Comment by amandalmia14** [comment]
Yes sure.

Thanks @bchevalier and others for the support you gave.
