### ISSUE TITLE
Question about creating model

### ISSUE THREAD

**Issue by gnatowski** [JWally/jsLPSolver#5]
Hi,
I found jsLPSolver while searching for nodejs module which could solve our problem. It is similar to your "Monster Problem". We have some shops which sell shoes. Some of them get demands on shoes which are not on stock and must be transported from other shops. The cost of transport is constant and not proportional to amount (or, maybe there a small additional fee for every shoe packed on truck). I can't imagine, how to create the model.

I started with
[{
	"name": "Transport problem",
	"optimize": "cost",
	"opType": "min",
	"constraints": {
		"shop1 demand article1": { "min": 5, "max": 5},
		"shop1 demand article2": { "min": 2, "max": 2},
		"shop2 demand article1": { "min":1, "max": 1},
		"shop2 demand article2": { "min": 3, "max": 3},
		"shop3 stock article1": { "max": 8},		
		"shop3 demand article2": { "min": 2, "max": 2},
		"shop4 stock article1": { "max": 3},
		"shop4 stock article2": { "max": 4},
		"shop5 demand article1": { "min": 2, "max": 2 },		
		"shop5 stock article2": { "max": 4 }
	},
	"variables": {
	}
}]
but how can I define the costs for transport?

**Comment by bchevalier** [comment]
"variables": {
        "brit": {
            "capacity": 20000,
            "plane": 1,
            "person": 8,
            "cost": 5000
        },
        "yank": {
            "capacity": 30000,
            "plane": 1,
            "person": 16,
            "cost": 9000
        }
    },
