### ISSUE TITLE
Example in README 

### ISSUE THREAD

**Issue by hotpeperoncino** [JWally/jsLPSolver#50]
Very low priority issue...
Example should be changed to

 var fs = require("fs"),
      solver = require("./src/solver"),
      model = {};

  // Read Data from File
  fs.readFile("./your/model/file", "utf8", function(e,d){
      // Convert the File Data to a JSON Model
      model = solver.ReformatLP(d);
  // Solve the LP
      console.log(solver.Solve(model));  // this line is changed
  });

**Comment by JWally** [comment]
good catch.
Thanks!
