### ISSUE TITLE
NPM version update

### ISSUE THREAD

**Issue by lvenerosy** [JWally/jsLPSolver#62]
@JWally could you update the version that is on NPM please ? Maybe you want to wait for the PR from @Toffi-123, but the patches from the last few PRs are critical enough to bump it up.

**Comment by JWally** [comment]
Sorry about that, can do.
Will try and move it up by eod saturday.
Thanks,
-JWW

**Comment by JWally** [comment]
Should be done.
Let me know if you have any issues.
Again, sorry for the delay.

**Comment by lvenerosy** [comment]
Thank you it's working !
