### ISSUE TITLE
Cutting Stock and Unexpected Result

### ISSUE THREAD

**Issue by danvanorden** [JWally/jsLPSolver#63]
The following model generates an unexpected result: 

```javascript
{
  "optimize": "cost",
  "opType": "min",
  "constraints": {
    "length": {
      "min": 25
    }
  },
  "variables": {
    "21": {
      "21": 1,
      "length": 21,
      "cost": 75
    },
    "26": {
      "26": 1,
      "length": 26,
      "cost": 90
    },
    "31": {
      "31": 1,
      "length": 31,
      "cost": 105
    },
    "36": {
      "36": 1,
      "length": 36,
      "cost": 120
    }
  },
  "ints": {
    "21": 1,
    "26": 1,
    "31": 1,
    "36": 1
  }
}
```

The result I get is: 

```javascript
{  
   "26":-0,
   "36":1,
   "feasible":true,
   "result":120,
   "bounded":true
}
```

What I'm trying to do is find the minimum number of panel lengths required to cover at least the minimum overall required length (the length of a building) while minimizing final cost of the panels. I believe this is a variation of of the cutting stock problem. In this case, the minimum required length is 25. I would expect the solver to return a result of "26": 1 rather than "36": 1. The cost in that case would be 90 rather than 120. 

I'm assuming I constructed the model incorrectly somehow. Is it possible to achieve my intended result with a modification to the model?

**Comment by JWally** [comment]
@bchevalier @lvenerosy any idea what's happening here? I'm get the same results.

Thanks,
-JWW

**Comment by lvenerosy** [comment]
Checking it today.

**Comment by lvenerosy** [comment]
This is a problem with the MIR cuts. Inside src/Model.js in the constructor Model, you can change ```this.useMIRCuts = true;``` to false.
I am not sure of when I will be able to patch it though.

**Comment by danvanorden** [comment]
Thanks for your insight and engagement on the issue. I'm using @lvenerosy's suggested workaround for now.

**Comment by JWally** [comment]
Sorry for the long delay. I removed some code, and I think it should work now like you're expecting. Can you re-test and if satisfied; close this? Thanks!

**Comment by JWally** [comment]
I'm think I got this cleaned up and am going to close. Feel free to re-open if I missed something.
