### ISSUE TITLE
Question about Multi-Objective Optimization

### ISSUE THREAD

**Issue by andrewheppner** [JWally/jsLPSolver#66]
Hey Guys,
Thanks so much for making this library accessible, it is a great help.

I had a question about your Multi-Objective Optimization solver.

I am trying to set up a scenario like this.

Say that you want to make an batch of Pudding.

You want the batch of Pudding to have a yield of 100g. 

In your pudding you have the following three ingredients:
-chocolate { fat: 5g/100g, carbs: 0g, protein: 0g, chocolate: 1}
- milk { fat: 0, carbs: 10g/100g, protein: 0, milk: 1}
-eggs  { fat: 0, carbs: 0g, protein: 13g/100g, eggs: 1}

Here are our constraints:
1. We want to make 100g of pudding.
2. We want the pudding to be 30% fat, 10%protein and 25% carb

How would we set up our model in such a way that allows you to enter a contraint that chocolate+ milk + eggs equals 100g?

```
const model = {
    "optimize": {
      // Do we need to add optimize here? If we don't what is the outcome?
    },
    "constraints": {
        'carb': { "equal": 25 },
        'fat': { "equal": 30 },   
        protein: { "equal": 10 },
        We want ... egg + chocolate + milk = 100
    },
    "variables": {
        "chocolate":  { fat: 5g/100g, carbs: 0g, protein: 0g, chocolate: 1},
        "milk": { fat: 0, carbs: 10g/100g, protein: 0, milk: 1},
        "egg": { fat: 0, carbs: 0g, protein: 13g/100g, eggs: 1}
    }
};
```

Note this example is probably not feasible value wise (as i just made it up) but i'm just curious about how to add the total value constraints of the 3 variables. I'm also curious if there is a way to constrain a variable using a min AND a mix?

THanks a TONNNNN.

Andrew

**Comment by elia-c** [comment]
I had had very similar problem, here it is my solution:

    let model = {
            "optimize": "price",
            "opType": "min",
            "constraints": {
                "mais": {"min": 30, "max": 80},
                "fieno": {"min": 2, "max": 50},
                "soia": {"min": 1, "max": 5},
                "girasole": {"min": 2, "max": 3},
                "colza": {"min": 0.1, "max": 3},
                "avena": {"min": 0.1, "max": 3},
                "calciocarb": {"min": 0.01, "max": 3},
                "tot": {"equal": 100},
            },
            "variables": {
                "mais": {
                    "price": 1,
                    "mais": 1,
                    "tot": 1,
                },
                "fieno": {
                    "price": 1,
                    "fieno": 1,
                    "tot": 1,
                },
                "soia": {
                    "price": 1,
                    "soia": 1,
                    "tot": 1,
                },
                "girasole": {
                    "price": 1,
                    "girasole": 1,
                    "tot": 1,
                },
                "colza": {
                    "price": 1,
                    "colza": 1,
                    "tot": 1,
                },
                "avena": {
                    "price": 1,
                    "avena": 1,
                    "tot": 1,
                },
                "calciocarb": {
                    "price": 1,
                    "calciocarb": 1,
                    "tot": 1,
                },
            }
        };

**Comment by JWally** [comment]
Sorry for the late response.

@elia-c nailed it. 

Just add a "fake" attribute to each thing with a value of 1; and in the constraints, set that attribute equal to 100 (or whatever you want the total amount to be).

```javascript
const model = {
    "optimize": "eggs",
    "opType": "max",
    "constraints": {
       'carb': { "max": 13.075413 },
       'fat': { "equal": 12.486736 },   
       'protein': { "equal": 9.846738 },
       'total_weight': {"equal": 100}
    },
    "variables": {
        "chocolate":  { fat: 0.3057, carbs: 0.5801, protein: 0.0851, chocolate: 1, total_weight: 1},
        "milk": { fat: 0.0325, carbs: 0.048, protein: 0.0315, milk: 1, total_weight: 1},
        "egg": { fat: 0.0951, carbs: 0.0072, protein: 0.1256, eggs: 1, total_weight: 1}
    }
};

```
