### ISSUE TITLE
Job Shop Scheduling Question 

### ISSUE THREAD

**Issue by kandres** [JWally/jsLPSolver#68]
I have been reading through your test problems and am trying to find one that could be used as an example to build a job shop scheduling optimization using your library. Is there one that could be mimicked for 450 variables and approx 10 constraints? If not, could this type of problem be solved with your library? I need to build a solution in JavaScript and your library seems to be the best shot.

**Comment by JWally** [comment]
Sorry for the delay. Not sure if its still useful information; but aside from processing time, I don't see an issue. There's a problem under test/test-sanity called "Monster_II.json" with 924 variables, 888 constraints, and 112 integer constraints. Hopefully that'll give you an idea of what this library can do and how to get started. Feel free to re-open this if you need some more help.
