### ISSUE TITLE
Multi-objective solver inifinite loop?

### ISSUE THREAD

**Issue by alenl** [JWally/jsLPSolver#73]
Hi @JWally , excellent library! Thank you so much for creating this, I really like your approach to specifying problems. Much more readable than tableaus.
I have an example where I think the multi-objective solver has a very weird lockup that probably shouldn't be happening. As far as I was able to debug it, it solves all the variations of the program correctly, and then when it tries to solve the "cheater" model in the end to find the midpoints, it seems to run forever. I was wandering if you are interested in this and want me to provide some sample data to reproduce this?
Thanks!

**Comment by JWally** [comment]
Hey @alenl ,

Sorry for the delay getting back to you. I'm just now getting some time to play with this again.

If you have some examples I could look at where it hangs, I'd love to look into it. Thanks!

-JWW

**Comment by alenl** [comment]
Sorry, I don't have that code anymore. It wasn't a static example, but a dataset that was generated by code from a simpler data input. I rewrote that completely since it wasn't working.
