### ISSUE TITLE
Return all or "top x" optimizations

### ISSUE THREAD

**Issue by jordanhaven** [JWally/jsLPSolver#74]
This is a re-ask from https://github.com/JWally/jsLPSolver/issues/46

@bchevalier mentioned that it wouldn't be too hard to add functionality for this, and it's definitely something I'd be interested in.

I would like to be able to return either all, or at least a specified amount, of the top feasible solutions to a problem.

I'm building a lineup generator where additional filtering/comparison needs to be done, so being able to get a few additional feasible solutions would be very helpful.

Thanks!

**Comment by jordanhaven** [comment]
Ended up coming back to this and figuring it out myself. It's certainly dirty right now, but maybe once I clean it up, I'll submit a PR :)

**Comment by JWally** [comment]
Please do!

**Comment by JWally** [comment]
Gonna close this (feel free to re|open another) to clean up this repo some. Also, on the model, you can add a tolerance option that exits when the mip is within a specified percentage of the optimal solution.
