### ISSUE TITLE
Urgent help needed to understand LP solve format for division

### ISSUE THREAD

**Issue by contactprad** [JWally/jsLPSolver#76]
we are trying to define the equation something like below:

" (a1 + b1 ) /( a1 + b1 + x1 + y1 )  >= 0.2" but that's not working.

What will be the document guidance for above? Thanks

**Comment by bchevalier** [comment]
Hey, this solver can only handle linear equations. are `a1` and `b1` variables? or are they constants?
if those are variables then you would need another solver. if they are constants they places the variables `x1` and `y1` on the other side of the constraint and try solving again

**Comment by contactprad** [comment]
ah ok! got it. a1 and a2 are variables indeed.
