### ISSUE TITLE
Returning a subset of possible solutions

### ISSUE THREAD

**Issue by alhambra1** [JWally/jsLPSolver#93]
Hi,

Is there a way to retrieve a subset of optimal solutions rather than just one? If you could even point me towards where to look to possibly tweak to accomplish that, that would be great.

Sincerely,

**Comment by JWally** [comment]
Are you looking for a subset of mixed-integer-LPs or just plain LP's?

**Comment by alhambra1** [comment]
At the moment, I'm using it with integers only.

**Comment by JWally** [comment]
https://github.com/JWally/jsLPSolver/blob/be561df57cc6cea45ad828b0dfc22cdc903c3c7f/src/Tableau/branchAndCut.js#L162-L175

This if block, between 161 and 175 is where the MILP has a valid solution.
You could add the following bit of code there:

```javascript
            //
            //
            //
            //
            //
            //
            var nowSolution = (this.model.tableau.getSolution());
            var store = nowSolution.generateSolutionSet();
            store.result = nowSolution.evaluation;
            
            if(!this.model.solutions){
                this.model.solutions = [];
            }
            
            this.model.solutions.push(store);
            //
            //
            //
            //
            //
            //
            //

```

and access them like this:

```javascript
        var a = solver.Solve(model,1e-8,true);
        console.log(a._tableau.model.solutions);
```

**Comment by alhambra1** [comment]
Thank you so much. I really appreciate it!

**Comment by JWally** [comment]
FWIW, it doesn't seem to slow down the solver too much; so its an option you can get at through:

```json
{
    "options": {
        "keep_solutions": true
    }
}
```

which puts the solutions on _tableau.model.solutions.

Next update I send, it'll be in there :-)

Hope it helps!
