### ISSUE TITLE
Version 0.4.20 doesn't work in the browser

### ISSUE THREAD

**Issue by DaanVandenBosch** [JWally/jsLPSolver#96]
I just upgraded from 0.4.5 to 0.4.20 and I get these errors using webpack:

```
./node_modules/javascript-lp-solver/src/External/lpsolve/main.js
Module not found: Error: Can't resolve 'child_process' in 'C:\Users\Daan\code\phantasmal-world\node_modules\javascript-lp-solver\src\External\lpsolve'
./node_modules/javascript-lp-solver/src/External/lpsolve/main.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\Daan\code\phantasmal-world\node_modules\javascript-lp-solver\src\External\lpsolve'
```

Is browser support no longer a feature?

Edit: 0.4.17 does work in the browser.

**Comment by JWally** [comment]
It is, and that’s on me...
I need better browser testing on my side.

Immediate solution?: Try using 4.16

I don’t have time to fix today but tomorrow I should.

What steps can I take to replicate its failure?

Are you bringing it in through a script tag?

Does it fail when you try and solve a model or when you call something else?

Are you building it yourself or using the one prebuilt in the package?

**Comment by DaanVandenBosch** [comment]
We're using it in this project: https://github.com/DaanVandenBosch/phantasmal-world (first line of this file: https://github.com/DaanVandenBosch/phantasmal-world/blob/master/src/hunt_optimizer/stores/HuntOptimizerStore.ts).

We use the package from npmjs (through yarn). And we use webpack to load it as a module. It's actually webpack that throws the error (before we can even load the module) because it can't find "child-process" and "fs", which are node built-in modules. The errors seem to stem from this file: https://github.com/JWally/jsLPSolver/blob/master/src/External/lpsolve/main.js

And 0.4.17 is the most recent version available on npmjs that does work and it's the version we're using at the moment.

**Comment by JWally** [comment]
I built out a better "test-suite" to make sure the library works in the browser.

1.) node server.js
2.) Aim a browser @ http://localhost:9000/test/test.html

However, I'm not sure if this helps you since it looks like webpack is what throws a fit when trying to compile everything...

Just curious, can you change what webpack compiles?

Right now, it looks like you're using /src/main.js.
What happens if you use /prod/solver.js?

**Comment by JWally** [comment]
@DaanVandenBosch , does this solve your issue?

**Comment by CXuesong** [comment]
I've actually applied a [patch](https://raw.githubusercontent.com/crystal-pool/warriors-family-tree/master/patch.diff) to mitigate this:
```diff
--- "a/node_modules/javascript-lp-solver/src/main.js"
+++ "b/node_modules/javascript-lp-solver/src/main.js"
@@ -25,7 +25,7 @@ var Constraint = expressions.Constraint;
 var Variable = expressions.Variable;
 var Numeral = expressions.Numeral;
 var Term = expressions.Term;
-var External = require("./External/main.js");
+var External = {};
 
 // Place everything under the Solver Name Space
 var Solver = function () {
```
